"use client"

// import type { Metadata } from "next";
import { Toaster } from 'sonner';
import { Jost } from 'next/font/google';

import { ThemeProvider } from "@/components/theme-provider";
import { LanguageProvider } from '@/components/language-context';

import "./globals.css";
const jost = Jost({
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${jost.className}  antialiased`} suppressHydrationWarning style={{ minHeight: '200vh' }}>
      <head />
      <body>
        <LanguageProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: { zIndex: 9999 },
            }}
          />
            {children}
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  )
}
