"use client"

// import type { Metadata } from "next";
import { Jost } from 'next/font/google';


import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { LanguageProvider } from '@/components/language-context';
import { Toaster } from 'sonner';

const jost = Jost({
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${jost.className}  antialiased`} suppressHydrationWarning>
      <head />
      <body>
        <Toaster />
        <LanguageProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  )
}
