import type { Metadata } from "next";

export const metadata: Record<string, Metadata> = {
  "pt-BR": {
    title: "Currículo Renato Marques",
    description:
      "Desenvolvedor Front-End Sênior com +15 anos de experiência em React, Next.js, Angular, TypeScript, React Native e Flutter. Certificado AWS Developer Associate.",
    keywords: [
      "Renato Marques",
      "Desenvolvedor Front-End",
      "Desenvolvedor Full Stack",
      "Front-End Sênior",
      "ReactJS",
      "NextJS",
      "Angular",
      "Vue.js",
      "TypeScript",
      "JavaScript",
      "React Native",
      "Flutter",
      "Tailwind CSS",
      "Shadcn UI",
      "Bootstrap",
      "Material UI",
      "Styled Components",
      "Node.js",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Prisma",
      "Drizzle",
      "Supabase",
      "Firebase",
      "APIs RESTful",
      "Context API",
      "Zustand",
      "GraphQL",
      "tRPC",
      "Microsserviços",
      "Stripe",
      "Convex",
      "BetterAuth",
      "AWS",
      "AWS Developer Associate",
      "UI/UX",
      "Git",
      "GitFlow",
      "Scrum",
      "Kanban",
      "OAuth",
      "JWT",
      "OWASP",
      "Segurança Web",
      "Docker",
      "Kubernetes",
      "CI/CD",
    ],
    authors: [{ name: "Renato Marques" }],
    creator: "Renato Marques",
    publisher: "Renato Marques",
    openGraph: {
      type: "website",
      url: "https://renatomf.is-a.dev",
      title: "Currículo Renato Marques",
      description:
        "Currículo online de Renato Marques — experiência, habilidades técnicas, educação e contato.",
      siteName: "Currículo Renato Marques",
      locale: "pt_BR",
    },
    twitter: {
      card: "summary_large_image",
      title: "Currículo Renato Marques",
      description:
        "Currículo online de Renato Marques — experiência, habilidades técnicas, educação e contato.",
    },
    alternates: {
      canonical: "https://renatomf.is-a.dev",
    },
  },

  "en-US": {
    title: "Resume Renato Marques",
    description:
      "Senior Front-End Developer with 15+ years of experience in React, Next.js, Angular, TypeScript, React Native and Flutter. AWS Developer Associate certified.",
    keywords: [
      "Renato Marques",
      "Front-End Developer",
      "Full Stack Developer",
      "Senior Front-End",
      "ReactJS",
      "NextJS",
      "Angular",
      "Vue.js",
      "TypeScript",
      "JavaScript",
      "React Native",
      "Flutter",
      "Tailwind CSS",
      "Shadcn UI",
      "Bootstrap",
      "Material UI",
      "Styled Components",
      "Node.js",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Prisma",
      "Drizzle",
      "Supabase",
      "Firebase",
      "RESTful APIs",
      "Context API",
      "Zustand",
      "GraphQL",
      "tRPC",
      "Microservices",
      "Stripe",
      "Convex",
      "BetterAuth",
      "AWS",
      "AWS Developer Associate",
      "UI/UX",
      "Git",
      "GitFlow",
      "Scrum",
      "Kanban",
      "OAuth",
      "JWT",
      "OWASP",
      "Web Security",
      "Docker",
      "Kubernetes",
      "CI/CD",
    ],
    authors: [{ name: "Renato Marques" }],
    creator: "Renato Marques",
    publisher: "Renato Marques",
    openGraph: {
      type: "website",
      url: "https://renatomf.is-a.dev",
      title: "Resume Renato Marques",
      description:
        "Online resume of Renato Marques — experience, technical skills, education, and contact information.",
      siteName: "Resume Renato Marques",
      locale: "en_US",
    },
    twitter: {
      card: "summary_large_image",
      title: "Resume Renato Marques",
      description:
        "Online resume of Renato Marques — experience, technical skills, education, and contact information.",
    },
    alternates: {
      canonical: "https://renatomf.is-a.dev",
    },
  },
};
